import { useEffect, useState, useRef } from 'react'
import { api } from './api'
const statuses = { pending: 'Aguardando aprovação', published: 'Publicados', hidden: 'Ocultos', rejected: 'Recusados' }
export default function CatalogAdmin() {
  const [status, setStatus] = useState('pending'), [page, setPage] = useState(1), [rows, setRows] = useState([]), [more, setMore] = useState(false), [meta, setMeta] = useState({ categories: [], amenities: [] }), [edit, setEdit] = useState(null), [message, setMessage] = useState(''), [busy, setBusy] = useState(false)
  const dialog = useRef(null)
  useEffect(() => { if (!edit) return; dialog.current.showModal(); const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = old } }, [edit?.id])
  async function load() { setBusy(true); setMessage(''); try { const [data, options] = await Promise.all([api.catalog(status, page), api.catalogMeta()]); setRows(data.entries); setMore(data.hasMore); setMeta(options) } catch (e) { setMessage(e.message) } finally { setBusy(false) } }
  useEffect(() => { load() }, [status, page])
  const change = (key, value) => setEdit({ ...edit, [key]: value })
  async function save(e) { e.preventDefault(); setBusy(true); try { await api.saveCatalog(edit.id, edit); setEdit(null); await load(); setMessage('Cadastro atualizado com sucesso.') } catch (e) { setMessage(e.message) } finally { setBusy(false) } }
  return <section className="catalog-admin"><div className="card"><h2>Catálogo de espaços e fornecedores</h2><p>Cadastros gratuitos, independentes da assinatura do sistema. Revise as informações e fotos antes de publicar.</p><div className="catalog-toolbar"><select aria-label="Status do catálogo" value={status} onChange={e => { setStatus(e.target.value); setPage(1) }}>{Object.entries(statuses).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><button type="button" onClick={load} disabled={busy}>Atualizar catálogo</button><a href="https://clubeon.rubli.com.br" target="_blank" rel="noreferrer">Abrir site público ↗</a></div></div>
    {message && <p role="status" className="notice">{message}</p>}
    {busy && !edit ? <p>Carregando catálogo…</p> : <div className="catalog-admin-grid">{rows.map(row => <article className="card" key={row.id}><img src={row.photos[0]} alt={row.name} /><h3>{row.name}</h3><p>{meta.categories.find(c => c.id === row.category)?.label} · {row.city}, {row.state}</p><p>Responsável: {row.ownerName}</p><button onClick={() => { setEdit(row); setMessage('') }}>Revisar e editar</button></article>)}</div>}
    {!busy && !rows.length && <div className="card">Nenhum cadastro nesta situação.</div>}
    <div className="catalog-toolbar"><button disabled={page === 1 || busy} onClick={() => setPage(page - 1)}>Anterior</button><span>Página {page}</span><button disabled={!more || busy} onClick={() => setPage(page + 1)}>Próxima</button></div>
    {edit && <dialog ref={dialog} className="catalog-review" onCancel={e => { e.preventDefault(); if (!busy) setEdit(null) }} aria-labelledby="catalog-review-title"><form onSubmit={save}><div className="catalog-toolbar"><h2 id="catalog-review-title">Revisar cadastro</h2><button type="button" onClick={() => setEdit(null)} disabled={busy}>Fechar</button></div><div className="catalog-photos">{edit.photos.map((p, i) => <a key={p} href={p} target="_blank" rel="noreferrer"><img src={p} alt={'Foto ' + (i + 1)} /></a>)}</div>
    <div className="catalog-fields">{[['name', 'Nome do negócio'], ['ownerName', 'Responsável (privado)'], ['email', 'E-mail (privado)'], ['phone', 'WhatsApp público'], ['city', 'Cidade'], ['state', 'UF'], ['neighborhood', 'Bairro'], ['website', 'Site de reservas / site público']].map(([key, label]) => <label key={key}>{label}<input value={edit[key] || ''} onChange={e => change(key, e.target.value)} required={['name', 'ownerName', 'phone', 'city', 'state'].includes(key)} maxLength={key === 'state' ? 2 : key === 'website' ? 300 : 160} /></label>)}<label>Categoria<select value={edit.category} onChange={e => change('category', e.target.value)}>{meta.categories.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>Capacidade (pessoas)<input type="number" min="0" max="100000" value={edit.capacity || 0} onChange={e => change('capacity', e.target.value)} /></label></div>
    <label>Descrição pública<textarea value={edit.description} maxLength="1800" required onChange={e => change('description', e.target.value)} /></label><fieldset><legend>Estrutura do espaço</legend>{meta.amenities.map(a => <label className="catalog-check" key={a.id}><input type="checkbox" checked={edit.amenities.includes(a.id)} onChange={e => change('amenities', e.target.checked ? [...edit.amenities, a.id] : edit.amenities.filter(v => v !== a.id))} />{a.label}</label>)}</fieldset>
    <label>Situação<select value={edit.status} onChange={e => change('status', e.target.value)}>{Object.entries(statuses).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>Observação interna<textarea maxLength="1000" value={edit.moderationNote} onChange={e => change('moderationNote', e.target.value)} /></label><p>Autorização de publicação recebida em {edit.consentAt ? new Date(edit.consentAt).toLocaleString('pt-BR') : '—'}. Nome do responsável, e-mail e observações não são exibidos no site.</p>{message && <p role="alert">{message}</p>}<button className="primary" type="submit" disabled={busy}>{busy ? 'Salvando…' : edit.status === 'published' ? 'Salvar e publicar' : 'Salvar cadastro'}</button></form></dialog>}
  </section>
}
