import { useEffect, useState } from 'react'
import { MessageCircle, KeyRound, RefreshCcw } from 'lucide-react'
import { api } from './api'
export default function CatalogAccessRequests({ onChanged, refreshToken = 0 }) {
  const [rows, setRows] = useState([]), [page, setPage] = useState(1), [more, setMore] = useState(false), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [issued, setIssued] = useState(null), [selected, setSelected] = useState({})
  async function load() { setBusy(true); try { const data = await api.catalogAccessRequests(page); setRows(data.requests); setMore(data.hasMore); setSelected({}) } catch (e) { setMessage(e.message) } finally { setBusy(false) } }
  useEffect(() => { load() }, [page, refreshToken])
  async function issue(row) {
    const ids = selected[row.id] || []
    if (!ids.length) return setMessage('Selecione os anúncios que pertencem a esse responsável.')
    setBusy(true); setMessage('')
    try { const data = await api.issueCatalogAccess(row.id, ids); setIssued(data); await load(); await onChanged?.() } catch (e) { setMessage(e.message) } finally { setBusy(false) }
  }
  async function dismiss(row) { if (!window.confirm('Arquivar este pedido de acesso?')) return; setBusy(true); try { await api.dismissCatalogAccess(row.id); await load(); await onChanged?.() } catch (e) { setMessage(e.message) } finally { setBusy(false) } }
  return <section className="catalog-access card"><div className="card-head"><h2><KeyRound size={20}/> Pedidos de acesso aos anúncios</h2><button onClick={load} disabled={busy}><RefreshCcw size={16}/> Atualizar pedidos</button></div><p>Confira o responsável, selecione os anúncios e gere o link. O WhatsApp abre com a mensagem pronta; você precisa enviá-la. O link permite definir ou recuperar a senha e vale por 24 horas.</p>{message && <p className="notice" role="alert">{message}</p>}{issued && <div className="catalog-issued"><h3>Link gerado. Envie agora pelo WhatsApp.</h3><a className="primary" href={issued.whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle size={17}/> Abrir WhatsApp e enviar acesso</a><label>Link de acesso<input readOnly value={issued.url} onFocus={e => e.target.select()}/></label><button onClick={async () => { try { await navigator.clipboard.writeText(issued.url); setMessage('Link copiado.') } catch { setMessage('Selecione e copie o link acima.') } }}>Copiar link</button><p>Válido até {new Date(issued.expiresAt).toLocaleString('pt-BR')}. Se não enviar agora, guarde o link antes de sair desta tela.</p></div>}{!busy && !rows.length && <p>Nenhum pedido de acesso pendente.</p>}<div className="catalog-inbox-list">{rows.map(row => <article key={row.id}><div><strong>WhatsApp: {row.phone}</strong><p>Pedido em {new Date(row.requestedAt).toLocaleString('pt-BR')}</p><fieldset><legend>Anúncios a liberar</legend>{row.entries.map(entry => <label key={entry.id} className="catalog-check"><input type="checkbox" checked={(selected[row.id] || []).includes(entry.id)} onChange={e => setSelected(prev => ({ ...prev, [row.id]: e.target.checked ? [...(prev[row.id] || []), entry.id] : (prev[row.id] || []).filter(id => id !== entry.id) }))}/>{entry.name}{entry.ownerName && ' · ' + entry.ownerName}</label>)}{row.entries.length > 100 && <p>Selecione no máximo 100 anúncios.</p>}</fieldset></div><div className="catalog-access-actions"><button className="primary" disabled={busy} onClick={() => issue(row)}><KeyRound size={16}/> Gerar link de acesso</button><button disabled={busy} onClick={() => dismiss(row)}>Arquivar pedido</button></div></article>)}</div><div className="catalog-toolbar"><button disabled={page === 1 || busy} onClick={() => setPage(page - 1)}>Anterior</button><span>Página {page}</span><button disabled={!more || busy} onClick={() => setPage(page + 1)}>Próxima</button></div></section>
}
