import { useEffect, useState, useRef } from 'react'
import { api } from './api'
const statuses = { pending: 'Cadastros antigos pendentes', published: 'Publicados', hidden: 'Ocultos', rejected: 'Recusados' }
const filters = { review: 'Novos anúncios para revisar', ...statuses }
export default function CatalogAdmin({ onChanged, requestedId, refreshToken = 0 }) {
  const [status, setStatus] = useState('review'), [page, setPage] = useState(1), [rows, setRows] = useState([]), [more, setMore] = useState(false), [meta, setMeta] = useState({ categories: [], amenities: [] }), [edit, setEdit] = useState(null), [message, setMessage] = useState(''), [busy, setBusy] = useState(false)
  const dialog = useRef(null)
  useEffect(() => { if (!edit) return; dialog.current.showModal(); const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = old } }, [edit?.id])
  async function load() { setBusy(true); setMessage(''); try { const [data, options] = await Promise.all([api.catalog(status, page), api.catalogMeta()]); setRows(data.entries); setMore(data.hasMore); setMeta(options) } catch (e) { setMessage(e.message) } finally { setBusy(false) } }
  useEffect(() => { load() }, [status, page, refreshToken])
  useEffect(() => {
    if (!requestedId) return
    let active = true
    api.catalogEntry(requestedId).then(row => { if (active) setEdit(row) }).catch(error => { if (active) setMessage(error.message) })
    return () => { active = false }
  }, [requestedId, refreshToken])
  async function reviewed(row) {
    setBusy(true); setMessage('')
    try { await api.saveCatalog(row.id, { ...row, status: 'published' }); await load(); await onChanged?.(); setMessage('Anúncio revisado e publicado.') }
    catch (error) { setMessage(error.message) } finally { setBusy(false) }
  }
  async function remove(row) {
    if (!window.confirm(`Excluir o anúncio “${row.name}”?\n\nO cadastro e as fotos serão apagados definitivamente e o anúncio sairá do catálogo. Essa ação não pode ser desfeita.`)) return
    setBusy(true); setMessage('')
    try { await api.deleteCatalog(row.id); setEdit(null); if (rows.length === 1 && page > 1) setPage(page - 1); else await load(); await onChanged?.(); setMessage('Anúncio e fotos excluídos do catálogo.') }
    catch (error) { setMessage(error.message) } finally { setBusy(false) }
  }
  const change = (key, value) => setEdit({ ...edit, [key]: value })
  async function save(e) { e.preventDefault(); setBusy(true); try { await api.saveCatalog(edit.id, edit); setEdit(null); await load(); await onChanged?.(); setMessage(edit.status === 'rejected' ? 'Anúncio recusado e retirado do site.' : 'Cadastro atualizado com sucesso.') } catch (e) { setMessage(e.message) } finally { setBusy(false) } }
  return <section className="catalog-admin"><div className="card"><h2>Catálogo de espaços e fornecedores</h2><p>Cadastros gratuitos, independentes da assinatura do sistema. Novos anúncios são publicados automaticamente. Confira as informações e fotos; recuse quando encontrar inconsistências.</p><div className="catalog-toolbar"><select aria-label="Status do catálogo" value={status} onChange={e => { setStatus(e.target.value); setPage(1) }}>{Object.entries(filters).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><button type="button" onClick={load} disabled={busy}>Atualizar catálogo</button><a href="https://clubeon.rubli.com.br" target="_blank" rel="noreferrer">Abrir site público ↗</a></div></div>
    {message && <p role="status" className="notice">{message}</p>}
    {busy && !edit ? <p>Carregando catálogo…</p> : <div className="catalog-admin-grid">{rows.map(row => <article className="card" key={row.id}><img src={row.photos[0]} alt={row.name} /><h3>{row.name}</h3><p>{meta.categories.find(c => c.id === row.category)?.label} · {row.city}, {row.state}</p><p>Responsável: {row.ownerName}</p><p className="catalog-public-status">{row.status === 'published' ? 'Publicado no site' : statuses[row.status]}{row.reviewStatus === 'new' && ' · Aguardando revisão'}</p><div className="catalog-row-actions"><button disabled={busy} onClick={() => { setEdit(row); setMessage('') }}>Revisar e editar</button>{(row.reviewStatus === 'new' || row.status === 'pending') && <button className="catalog-confirm" disabled={busy} onClick={() => reviewed(row)}>{row.status === 'pending' ? 'Publicar e revisar' : 'Marcar como revisado'}</button>}<button className="catalog-reject" disabled={busy} onClick={() => { setEdit({ ...row, status: 'rejected' }); setMessage('') }}>Recusar anúncio</button><button className="catalog-delete" disabled={busy} onClick={() => remove(row)}>Excluir anúncio</button></div></article>)}</div>}
    {!busy && !rows.length && <div className="card">Nenhum cadastro nesta situação.</div>}
    <div className="catalog-toolbar"><button disabled={page === 1 || busy} onClick={() => setPage(page - 1)}>Anterior</button><span>Página {page}</span><button disabled={!more || busy} onClick={() => setPage(page + 1)}>Próxima</button></div>
    {edit && <dialog ref={dialog} className="catalog-review" onCancel={e => { e.preventDefault(); if (!busy) setEdit(null) }} aria-labelledby="catalog-review-title"><form onSubmit={save}><div className="catalog-toolbar"><h2 id="catalog-review-title">Revisar cadastro</h2><button type="button" onClick={() => setEdit(null)} disabled={busy}>Fechar</button></div><div className="catalog-photos">{edit.photos.map((p, i) => <a key={p} href={p} target="_blank" rel="noreferrer"><img src={p} alt={'Foto ' + (i + 1)} /></a>)}</div>
    <div className="catalog-fields">{[['name', 'Nome do negócio'], ['ownerName', 'Responsável (privado)'], ['email', 'E-mail (privado)'], ['phone', edit.type === 'space' && (edit.onlineBooking ?? !!edit.website) ? 'WhatsApp do responsável (privado)' : 'WhatsApp público'], ['city', 'Cidade'], ['state', 'UF'], ['neighborhood', 'Bairro'], ['website', 'Site de reservas / site público']].map(([key, label]) => <label key={key}>{label}<input value={edit[key] || ''} onChange={e => change(key, e.target.value)} required={['name', 'ownerName', 'phone', 'city', 'state'].includes(key) || (key === 'website' && edit.type === 'space' && (edit.onlineBooking ?? !!edit.website))} maxLength={key === 'state' ? 2 : key === 'website' ? 300 : 160} /></label>)}<label>Categoria<select value={edit.category} onChange={e => setEdit({ ...edit, category: e.target.value, type: meta.categories.find(c => c.id === e.target.value)?.type, onlineBooking: meta.categories.find(c => c.id === e.target.value)?.type === 'space' && (edit.onlineBooking ?? !!edit.website) })}>{meta.categories.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>Capacidade (pessoas)<input type="number" min="0" max="100000" value={edit.capacity || 0} onChange={e => change('capacity', e.target.value)} /></label></div>
    {edit.type === 'space' && <><label className="catalog-check"><input type="checkbox" checked={edit.onlineBooking ?? !!edit.website} onChange={e => change('onlineBooking', e.target.checked)}/> Receber reservas pelo site de agendamento</label><p>Com esta opção, o anúncio mostra apenas o botão de reservas. O WhatsApp fica privado para contato da equipe e acesso ao anúncio.</p></>}
    <label>Descrição pública<textarea value={edit.description} maxLength="1800" required onChange={e => change('description', e.target.value)} /></label><fieldset><legend>Estrutura do espaço</legend>{meta.amenities.map(a => <label className="catalog-check" key={a.id}><input type="checkbox" checked={edit.amenities.includes(a.id)} onChange={e => change('amenities', e.target.checked ? [...edit.amenities, a.id] : edit.amenities.filter(v => v !== a.id))} />{a.label}</label>)}</fieldset>
    <label>Situação<select value={edit.status} onChange={e => change('status', e.target.value)}>{Object.entries(statuses).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>{edit.status === 'rejected' ? 'Motivo da recusa (interno)' : 'Observação interna'}<textarea required={edit.status === 'rejected'} maxLength="1000" value={edit.moderationNote} onChange={e => change('moderationNote', e.target.value)} /></label><p>Autorização de publicação recebida em {edit.consentAt ? new Date(edit.consentAt).toLocaleString('pt-BR') : '—'}. Nome do responsável, e-mail e observações não são exibidos no site.</p>{message && <p role="alert">{message}</p>}<button className="primary" type="submit" disabled={busy}>{busy ? 'Salvando…' : edit.status === 'rejected' ? 'Recusar e retirar do site' : edit.status === 'published' ? 'Salvar e concluir revisão' : 'Salvar cadastro'}</button><button className="catalog-delete" type="button" disabled={busy} onClick={() => remove(edit)}>Excluir anúncio</button></form></dialog>}
  </section>
}
