import { useEffect, useState } from 'react'
import { KeyRound, MessageCircle } from 'lucide-react'
import { api } from './api'
function Delivery({ data }) {
  if (!data) return null
  return <div className="club-access-delivery"><p>Link gerado. Envie ao número cadastrado; o envio é manual.</p><a className="access-panel-link" href={data.whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle size={17}/> Abrir WhatsApp para enviar</a><label>Link de acesso<input readOnly value={data.url} onFocus={e => e.target.select()}/></label><small>Válido até {new Date(data.expiresAt).toLocaleString('pt-BR')} · uso único.</small></div>
}
export function ClubPasswordAccess({ club }) {
  const [busy, setBusy] = useState(false), [data, setData] = useState(null), [error, setError] = useState('')
  return <section className="club-password-access"><h3><KeyRound size={18}/> Acesso ao painel do clube</h3><p>{club.demoMode ? 'Demonstração: o painel é aberto sem senha. Desative a demonstração para gerar um link de senha.' : club.adminPasswordConfigured ? 'Senha cadastrada. Gere um link para o proprietário definir uma nova senha.' : 'Primeiro acesso pendente. Envie um link para o proprietário cadastrar a senha.'}</p><button className="club-access-primary" disabled={busy || club.demoMode} onClick={async () => { setBusy(true); setError(''); try { setData(await api.createAdminAccessLink(club.id, club.adminPasswordConfigured ? 'reset' : 'first-access')) } catch (e) { setError(e.message) } finally { setBusy(false) } }}><KeyRound size={16}/>{busy ? 'Gerando…' : club.adminPasswordConfigured ? 'Redefinir senha' : 'Gerar primeiro acesso'}</button>{error && <p role="alert">{error}</p>}{!club.demoMode && <Delivery data={data}/>}</section>
}
export function ClubRecoveryRequests({ refreshToken, onChanged }) {
  const [rows, setRows] = useState([]), [count, setCount] = useState(0), [busy, setBusy] = useState(false), [data, setData] = useState(null), [error, setError] = useState('')
  async function load() { const result = await api.clubRecoveryRequests(); setRows(result.requests); setCount(result.count) }
  useEffect(() => { let active = true; api.clubRecoveryRequests().then(result => { if (active) { setRows(result.requests); setCount(result.count) } }).catch(e => { if (active) setError(e.message) }); return () => { active = false } }, [refreshToken])
  async function act(row, issue) { setBusy(true); setError(''); try { if (issue) setData(await api.issueClubRecovery(row.clubId)); else { if (!window.confirm('Arquivar este pedido de recuperação?')) return; await api.dismissClubRecovery(row.clubId) } await load(); await onChanged?.() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  return <section className="club-recovery-inbox"><div className="card-head"><h2><KeyRound size={20}/> Recuperação de senha dos clubes {count > 0 && <span className="catalog-count">{count}</span>}</h2><button onClick={() => load().catch(e => setError(e.message))}>Atualizar pedidos de senha</button></div><p>Confira o clube e o responsável. O link será enviado pelo WhatsApp cadastrado no Master.</p>{error && <p role="alert" className="notice">{error}</p>}<Delivery data={data}/>{!rows.length && <p>Nenhum pedido de recuperação pendente.</p>}<div className="catalog-inbox-list">{rows.map(row => <article key={row.clubId}><div><strong>{row.name}</strong><p>{row.ownerName} · {row.phone}</p><small>Solicitado em {new Date(row.requestedAt).toLocaleString('pt-BR')}</small></div><div className="catalog-access-actions"><button className="club-access-primary" disabled={busy || !row.available} onClick={() => act(row, true)}>Gerar link de recuperação</button><button disabled={busy} onClick={() => act(row, false)}>Arquivar pedido de senha</button></div></article>)}</div>{count > rows.length && <p>Mostrando os 50 pedidos mais recentes. Após atendê-los, atualize para ver os demais.</p>}</section>
}
